apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: pipeline-buildconfig-template
message: A new pipeline buildconfig ${NAME} has been created in your project.
metadata:
  name: pipeline-buildconfig-template
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    # annotations:
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${BRANCH}
        uri: ${REPO_URL}
    #   sourceSecret:
    #     name: bitbucket      
      type: Git
    strategy:
      jenkinsPipelineStrategy: 
        jenkinsfilePath: ${JENKINSFILEPATH}
      type: JenkinsPipeline
    triggers:
    - type: ConfigChange
parameters:
- name: NAME
  description: pipeline name
  displayName: NAME
  value: 
- name: REPO_URL
  description: REPO_URL
  displayName: REPO_URL
  value: 
- name: BRANCH
  description: BRANCH
  displayName: BRANCH
  value: master
- name: CONTEXT_DIR
  description: CONTEXT_DIR 
  displayName: CONTEXT_DIR
  value: 
- name: JENKINSFILEPATH
  description: JENKINSFILEPATH
  displayName: JENKINSFILEPATH
  value: 
