  - name: Set variables for this iteration of the loop.
    set_fact:
      stage_name="{{ outer_item }}"
      stage_map="{{ stiu[outer_item] }}"
      cluster="{{ stiu[outer_item]['cluster'] }}"
      namespace="{{ stiu[outer_item]['namespace'] }}"
      maven_build="{{ stiu[outer_item]['maven_build']    | default(false) | bool }}"
      tag_to="{{ stiu[outer_item]['tag_to']         | default('UNKNOWN TAG-TO') }}"
      copy_from_stage_name="{{ stiu[copy_from_stage] | default() }}"
      
  - name: Set dependant variables for this iteration of the loop.
    set_fact:
      copy_from_stage_map="{{ stiu[copy_from_stage_name] }}"    
    when: {{ copy_from_stage_name }}
      
  - name: debug 
    debug:
      msg: |
        cluster:    {{ cluster }}
        stage_name: {{ stage_name }}
        Namespace:  {{ namespace }}
        options: 
            Maven-build: {{ maven_build }}
            Tag:         {{ tag_to }}
            copy-from:   {{ copy_from_stage_name | default('n/a') }}
        ---
        {{ stage_map | to_nice_yaml }}

  # - name: debug 
  #   debug:
  #     msg: |
  #         stage_name:      "{{ stage_name }}"
  #         cluster:         "{{ cluster }}"
  #         namespace:       "{{ namespace }}"
  #         maven_build:     "{{ maven_build }}"
  #         tag_to:          "{{ tag_to }}"
  #         tag_from_stage:  "{{ tag_to }}"    
  #         ---------------------------------------------------------
  #         stage_map:       ""
  #         ---------------------------------------------------------  
  #         stage_from_map:  ""
  #         ---------------------------------------------------------  
              
  #         Setup Complete