- name: Loop Info {{ outer_item }}
  debug: msg="processing stage '{{ outer_item }}'"

- name: Set variables for this iteration of the loop.
  set_fact:
    stage_name:   "{{ outer_item }}"
    stage_map:    "{{ stiu[outer_item] }}"
    cluster:      "{{ stiu[outer_item]['cluster'] }}"
    namespace:    "{{ stiu[outer_item]['namespace'] }}"
    maven_build:  "{{ stiu[outer_item]['maven_build']    | default(false) | bool }}"
    image_tag:    "{{ stiu[outer_item]['image_tags'] }}"
    has_jenkins:  "{{ stiu[outer_item]['has_jenkins']    | default(false) }}"
    copy_from_stage_name: "{{ stiu[outer_item]['copy_from_stage'] | default() }}"
    
- name: Set dependant variables for this iteration of the loop.
  set_fact:
    copy_from_stage_map="{{ stiu[copy_from_stage_name] }}"    
  when: 'copy_from_stage_name | length > 0'
    
- name: Print Stage Variables 
  debug:
    msg: |
      cluster:    {{ cluster }}
      stage_name: {{ stage_name }}
      Namespace:  {{ namespace }}
      options: 
          Maven-build: {{ maven_build }}
          Tag:         {{ image_tag }}
          copy-from:   {{ copy_from_stage_name if (copy_from_stage_name | length > 0) else 'n/a' }}
      
      --- STAGE MAP: ---
      {{ stage_map | to_nice_yaml }}

      --- STAGE MAP To COPY FROM: ---
      {{ copy_from_stage_map | default() | to_nice_yaml }}
      ---
      
      Setup Complete
