---

# {{outer_item}} is the stage-name set in the main loop outside!

- name: LOOP INFO {{ outer_item | upper }} 
  debug: 
    msg: |
      |
      =======================================================
      |
      |   CREATE PROJECTS - processing stage '{{ outer_item }}'
      |
      =======================================================
      |


- name: Include variable validation and set_facts for this loop iteration
  include_tasks: 099-check-set-facts.yaml


- name: Create Project {{ namespace }}
  k8s:
    kind: Project
    name: "{{ namespace }}"
    state: present  
  

#  jenkins SA needs custom permissions to update/patch namespaces!    
- name: Annotate Namespace {{ namespace }}
  k8s:
    kind: Namespace
    name: "{{ namespace }}"
    state: present 
    definition: "{{ lookup('template', 'templates/project_annotations.yaml') }}"
  loop: "{{ annotations | dict2items }}"


#  jenkins SA needs custom permissions to update/patch namespaces!    
- name: Label Namespace {{ namespace }}
  k8s:
    kind: Namespace
    name: "{{ namespace }}"
    state: present 
    definition: "{{ lookup('template', 'templates/project_labels.yaml') }}"
  loop: "{{ labels | dict2items }}"

- name: Print success msg
  debug:
    msg: |
      CREATE PROJECTS DONE for stage {{ outer_item }}
    verbosity: 0

