---
- name: LOOP INFO {{ outer_item | upper }} 
  debug: 
    msg: |
      |
      =======================================================
      |
      |   SETUP Jenkins in stage '{{ outer_item }}'
      |
      =======================================================
      |


- name: Include variable validation and set_facts for this loop iteration
  include_tasks: 099-check-set-facts.yaml


- name: Create Project {{ namespace }}
  k8s:
    kind: Project
    name: "{{ namespace }}"
    state: present  
  

- name: Create Jenkins Serviceaccount in Jenkins-Stage 
  k8s:
    kind: ServiceAccount
    namespace: "{{ namespace }}"
    state: present 
    definition:
      metadata:
        name: jenkins


- name: Set variables.
  set_fact:
    manifest_directory: "{{ JENKINS_WORKSPACE }}/{{ jenkins_manifest_dir }}"

#     manifest_lookup_type: "{{ outer_item.lookup_type | default('template') }}"
#     manifest_namespace: "{{ outer_item.namespace | default('') }}"


# - name: Include vars specific to this manifest.
#   include_vars: "{{ item }}"
#   with_first_found:
  #     - files:
    #         - "{{ manifest_directory }}/templates/vars.yml"
    #       skip: true
   
- name: Print current manifest directory.
  debug: var=manifest_directory


- name: Find Openshift templates in "{{ jenkins_manifest_dir }}/templates"
  find:
    paths: "{{ manifest_directory }}/templates"
    file_type: file
    patterns: '*.TEMPLATE.yaml'
    recurse: no
  register: templates


- name: print #TEMPLATES
  debug:
    msg: |
      Templates found: {{ templates.matched }}


- name: Process Templates
  include_tasks: 990-process-template.yaml
  loop: 
    - "{{ templates.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: loopitem_template 


- name: Print success msg
  debug:
    msg: |
      JENKINS SETUP DONE in stage {{ outer_item }}
    verbosity: 0
