---
- name: LOOP INFO {{ outer_item | upper }} 
  debug: 
    msg: |
      |
      =======================================================
      |
      |   SETUP Jenkins in stage '{{ outer_item }}'
      |
      =======================================================
      |


- name: Include variable validation and set_facts for this loop iteration
  include_tasks: 099-check-set-facts.yaml


- name: Create Project {{ namespace }}
  k8s:
    kind: Project
    name: "{{ namespace }}"
    state: present  
  

- name: Create Jenkins Serviceaccount in Jenkins-Stage 
  k8s:
    kind: ServiceAccount
    namespace: "{{ namespace }}"
    state: present 
    definition:
      metadata:
        name: jenkins


- name: Set variables.
  set_fact:
    manifest_directory: "{{ JENKINS_WORKSPACE }}/{{ jenkins_manifest_dir }}"

#     manifest_lookup_type: "{{ outer_item.lookup_type | default('template') }}"
#     manifest_namespace: "{{ outer_item.namespace | default('') }}"


# - name: Include vars specific to this manifest.
#   include_vars: "{{ item }}"
#   with_first_found:
  #     - files:
    #         - "{{ manifest_directory }}/templates/vars.yml"
    #       skip: true
   
- name: Print current manifest directory.
  debug: var=manifest_directory


- name: Find Openshift templates in "{{ jenkins_manifest_dir }}/templates"
  find:
    paths: "{{ manifest_directory }}/templates"
    file_type: file
    patterns: '*.TEMPLATE.yaml,*.TEMPLATE.yml'
    recurse: no
  register: templates

- name: print TEMPLATES found
  debug:
    msg: |
      Template: {{ item }}
    verbosity: 1
  loop: "{{ templates.files | map(attribute='path') | list }}"


- name: Find PARAMETER files
  set_fact:
    param_files: "{{ param_files | default([])  +  [ item | replace('.TEMPLATE.', '.PARAMETERS.') ] }}"
  loop: "{{ templates.files | map(attribute='path') | list }}"


- name: print TEMPLATES found
  debug:
    msg: |
      Template: {{ item.0 }}
      Params:   {{ item.1 }}
  with_together: 
    - "{{ templates.files | map(attribute='path') | list }}"
    - "{{ param_files }}"



- name: Process & apply template
  shell: |
    {{ OC_CMD }} -n {{ namespace }} process -f {{ item.0}} --param-file={{ item.1 }} -o yaml | {{ OC_CMD }}  -n {{ namespace }} apply -f -
  with_together: 
    - "{{ templates.files | map(attribute='path') | list }}"
    - "{{ param_files }}"    
  register: ocOut

- name: print ocOut
  debug:
    msg: |
      --- std-out ---
      {{ item.stdout }}
      --- std-err ---
      {{ item.stderr }}
  loop: "{{ ocOut.results }}" 


# - name: 
# - name: Deploy the resources defined inside the manifest.
#   k8s:
#     definition: "{{ item }}"
#     state: present
#     force: "{{ k8s_force }}"
#   loop: "{{ lookup('file', manifest_directory + '/  .yml') | from_yaml_all | list }}"
#   register: k8s_result
#   until: k8s_result is success
#   retries: 10
#   delay: 2
#   no_log: "{{ k8s_no_log }}"




- name: Print success msg
  debug:
    msg: |
      JENKINS SETUP DONE in stage {{ outer_item }}
    verbosity: 0
