---
- name: LOOP INFO {{ outer_item | upper }} 
  debug: 
    msg: |
      |
      =======================================================
      |
      |   RBAC SETUP - processing stage '{{ outer_item }}'
      |
      =======================================================
      |


- name: Include variable validation and set_facts for this loop iteration
  include_tasks: 099-check-set-facts.yaml


- name: Print someting
  debug:
    msg: |
      RBAC SETUP DONE
    verbosity: 0



# - name: Allow image pulling from Jenkins namespace
#   k8s:
#     kind: Namespace
#     name: "{{ namespace }}"
#     state: present 
#     definition: "{{ lookup('template', 'templates/project_labels.yaml') }}"
#   when: 'stage_name == jenkins_stage'




# // this pipeline requires permissions 
#   // 1) for all SA in this namespace to pull images from in IMAGE_NAMESPACE:
#   //     oc -n $IMAGE_NAMESPACE policy add-role-to-group system:image-puller system:serviceaccounts:$NAMESPACE`
#   // 2) for Jenkins SA in ns: uits-ukms-int to edit/admin resources
#   //     oc -n $NAMESPACE policy add-role-to-user admin system:serviceaccount:uits-ukms-int:jenkins-ukms
