---

- name: Check required stage variables - {{outer_item}}
  fail:
    msg: "Variable {{outer_item}} : {{ item }} is not defined!"  
  when: 'stiu[outer_item][item] is undefined'
  loop_control:
    label: "checking var: {{outer_item}} : {{ item }}"       
  loop:
    - 'namespace'
    - 'cluster'
    - 'image_tag'


- name: Set variables for this iteration of the loop - {{outer_item}}
  set_fact:
    stage_name:   "{{ outer_item }}"
    namespace:    "{{ stiu[outer_item]['namespace'] }}"
    cluster:      "{{ stiu[outer_item]['cluster'] }}"
    image_tag:    "{{ stiu[outer_item]['image_tag'] }}"
    stage_map:    "{{ stiu[outer_item] }}"
    maven_build:  "{{ stiu[outer_item]['maven_build']    | default(false) | bool }}"
    copy_from_stage_name: "{{ stiu[outer_item]['copy_from_stage'] | default() }}"


- name: Set dependant variables for this iteration of the loop - {{outer_item}}
  set_fact:
    copy_from_stage_map:  "{{ stiu[copy_from_stage_name] | default({}) }}"    

# - name: Set dependant^2 variables for this iteration of the loop - {{outer_item}}
#   set_fact:


- name: Print Stage Variables - {{outer_item}}
  debug:
    msg: |
      Cluster:    {{ cluster }}
      Stage_name: {{ stage_name }}
      Namespace:  {{ namespace }}
      options: 
          Maven-build: {{ maven_build }}
          Tag:         {{ image_tag }}
          copy-from:   {{ copy_from_stage_name if (copy_from_stage_name | length > 0) else 'n/a' }}
      
      Jenkins in stage:       {{ jenkins_stage }}
      Jenkins in namespace:   {{ jenkins_namespace }}
      Stages-without-Jenkins: {{ stages_without_jenkins }}
      
      --- STAGE MAP: ---
      {{ stage_map | to_nice_yaml }}

      --- STAGE MAP To COPY FROM: ---
      {{ copy_from_stage_map | to_nice_yaml }}
      ---
      
    verbosity: 0

