---

- name: Check required top-level variables 
  fail:
    msg: "Variable {{ item }} is not defined!"  
  when: 'stiu[item] is undefined'
  loop_control:
    label: "checking var: {{ item }}"       
  loop:
    - 'repository'
    - 'jenkins_stage'
    - 'cluster_authentication'

- name: Check required stage variables - {{outer_item}}
  fail:
    msg: "Variable {{outer_item}} : {{ item }} is not defined!"  
  when: 'stiu[outer_item][item] is undefined'
  loop_control:
    label: "checking var: {{outer_item}} : {{ item }}"       
  loop:
    - 'namespace'
    - 'cluster'
    - 'image_tag'


- name: Set variables for this iteration of the loop - {{outer_item}}
  set_fact:
    repository:   "{{ stiu.repository }}"
    stage_name:   "{{ outer_item }}"
    namespace:    "{{ stiu[outer_item]['namespace'] }}"
    cluster:      "{{ stiu[outer_item]['cluster'] }}"
    image_tag:    "{{ stiu[outer_item]['image_tag'] }}"
    stage_map:    "{{ stiu[outer_item] }}"
    maven_build:  "{{ stiu[outer_item]['maven_build']    | default(false) | bool }}"
    copy_from_stage_name: "{{ stiu[outer_item]['copy_from_stage'] | default() }}"

    annotations:   "{{ stiu.project_annotations | default({}) }}"
    labels:        "{{ stiu.project_labels | default({}) }}"
    jenkins_stage: "{{ stiu.jenkins_stage }}"
    cluster_auth:  "{{ stiu.cluster_authentication | default({}) }}"


- name: Set dependant variables for this iteration of the loop - {{outer_item}}
  set_fact:
    copy_from_stage_map:  "{{ stiu[copy_from_stage_name] | default({}) }}"    
    jenkins_namespace:    "{{ stiu[jenkins_stage]['namespace'] }}"    
    non_jenkins_namespace_list: "{{ stiu.stages | reject('search', jenkins_namespace) | list }}"    


- name: Print Stage Variables - {{outer_item}}
  debug:
    msg: |
      Cluster:    {{ cluster }}
      Stage_name: {{ stage_name }}
      Namespace:  {{ namespace }}
      options: 
          Maven-build: {{ maven_build }}
          Tag:         {{ image_tag }}
          copy-from:   {{ copy_from_stage_name if (copy_from_stage_name | length > 0) else 'n/a' }}
      
      Jenkins in: {{ jenkins_namespace }}
      Not Jenkins namespace list:
                  {{ non_jenkins_namespace_list }}
      
      --- STAGE MAP: ---
      {{ stage_map | to_nice_yaml }}

      --- STAGE MAP To COPY FROM: ---
      {{ copy_from_stage_map | to_nice_yaml }}
      ---
      
    verbosity: 0

